### ISSUE TITLE
install Salla CLI

### ISSUE THREAD

**Issue by TalalAlerwi** [SallaApp/Salla-CLI#71]
i-m trying To install Salla CLI but i got this error ! need help. 

`Last login: Sun Jun  2 22:00:40 on ttys011
abdulaziz@MacBook-Air-Talals salla % npm install @salla.sa/cli -g
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/@salla.sa
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@salla.sa'
npm error     at async mkdir (node:internal/fs/promises:855:10)
npm error     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:624:20
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/local/lib/node_modules/@salla.sa'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

npm error A complete log of this run can be found in: /Users/abdulaziz/.npm/_logs/2024-06-02T19_01_02_501Z-debug-0.log
abdulaziz@MacBook-Air-Talals salla % 
`

**Comment by TheYass1n** [comment]
I get the same err, did you find any solution

**Comment by TheYass1n** [comment]
I have solve it by install `softwareupdate --install-rosetta`
